language: ruby

services:
  - rabbitmq

env:
  - JRUBY_OPTS="--dev -Xcext.enabled=false -Xcompile.invokedynamic=false"

rvm:
  - jruby-1.7.16
  - jruby-head

bundler_args: --deployment --binstubs --jobs=3 --retry=3

cache: bundler

jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7

sudo: false

before_script: cp config/worker.example.yml config/worker.yml

script: bin/rspec spec

matrix:
  allow_failures:
    - rvm: jruby-head