queue: builds
shell:
  buffer: 1.5
vms:
  count: 5
  base: lucid32_old
  memory: 1536
  cookbooks: 'vendor/cookbooks/vagrant_base'
  log_level: 'info'
  json:
    rvm:
      rubies:
        - 1.8.7
        - 1.9.2
        - 1.9.3
        - jruby
        - rbx
        - ree
        - ruby-head
      gems:
        - bundler
        - rake
        - chef
      aliases:
        rbx-2.0: rbx
        rbx-2.0.0pre: rbx
    nodejs:
      versions:
        - 0.4.11
        - 0.5.5
    mysql:
      server_root_password: ""
    postgresql:
      max_connections: 256
    travis_build_environment:
      use_tmpfs_for_builds: false
  recipes:
    - travis_build_environment
    - apt
    - build-essential
    - scons
    - networking_basic
    - openssl
    - sysctl
    - libyaml # libyaml MUST be installed before rubies. MK.
    - emacs::nox
    - vim
    - timetrap
    - git
    - java
    - ant
    - maven
    - leiningen
    - libqt4
    - libv8
    - nodejs
    - rvm
    - rvm::multi
    - sqlite
    - postgresql::client
    - postgresql::server
    - mysql::client
    - mysql::server
    - redis
    - riak
    - mongodb
    - couchdb
    - memcached
    - rabbitmq::with_management_plugin
    - imagemagick
    - sphinx::all
    - xserver
    - firefox
    - kerl
    - python
    - python::multi
