queue: builds
shell:
  buffer: 1.5
vms:
  count: 5
  base: lucid32_old
  memory: 1536
  cookbooks: 'vendor/cookbooks/vagrant_base'
  log_level: 'info'
  json:
    rvm:
      rubies:
        - 1.8.7
        - 1.9.2-head
        - 1.9.3
        - jruby
        - rbx
        - rbx-2.0.0pre
        - ree
        - ruby-head
        - 1.9.1-p378
        - 1.8.7-p249
        - 1.8.6
      gems:
        - bundler
        - rake
        - chef
      aliases:
        rbx-2.0.0pre: rbx-2.0
        1.9.1-p378:   1.9.1
        1.9.2-head:   1.9.2
    mysql:
      server_root_password: ""
    postgresql:
      max_connections: 256
  recipes:
    - travis_build_environment
    - apt
    - build-essential
    - scons
    - networking_basic
    - openssl
    - sysctl
    - libyaml # libyaml MUST be installed before rubies. MK.
    - emacs::nox
    - vim
    - timetrap
    - git
    - java
    - ant
    - maven
    - leiningen
    - libqt4
    - libv8
    - nodejs
    - rvm
    - rvm::multi
    - sqlite
    - postgresql::client
    - postgresql::server
    - mysql::client
    - mysql::server
    - redis
    - riak
    - mongodb
    - memcached
    - rabbitmq
    - imagemagick
    - sphinx
    - xserver